apiVersion: v1
kind: Service
metadata:
  name: dotnet-course
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: dotnet-course
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080